Added new Parameter-Entity system + bunch of new features(Better configurations files + Technology trees + FOW...) (#30)
* Added Navigation  and too many other things(#1)

* Added navmesh generation and pathfinding + Added multi unit selection

* Cleaned CMakeList + Removed unnecesary files

* Fixed unit selection from enemies

* Added attack action(If the unit is not in range, move to a closer position) + Fixed units stop attacking

* Fixed units healing more than maxHealth + Cleaned code

* Enable draw debug in RTS

* added temp stats summary

* Implement fps tests for rts game

* Fix playerCount wrong in some situations

* Fixed Arena logging correct number of Turns + Fixed Arena building navmesh

* Fixed Navmesh generation crash

* Fixed Test crash building navmesh

* Cleaned CMakeList + GridUtils

* Cleaned Grid Utils

* Removed StatsSummary(Not used rigth now)

* Cleaned small changes

Co-authored-by: Dominik Jeurissen <dominik.jeurissen@student.maastrichtuniversity.nl>

* Fixed  healing TBS + Fixed race problem with communictor + WinConditi… (#2)

* Fixed  healing TBS + Fixed race problem with communictor + WinCondition during fogOfWar + RHEA agent stuck genome

* Removed TBS Unit max health attribute

* Cleaned

* RTS execute single actions

Co-authored-by: Dominik Jeurissen <dominik.jeurissen@student.maastrichtuniversity.nl>

* Implement win condition for RTS games + Fog of war (#4)

* Make agents parameters configurable via YAML-files

* unfinished parameters for agents

* Complete feature

Co-authored-by: Dominik Jeurissen <dominik.jeurissen@student.maastrichtuniversity.nl>

* Too many changes to agents

* fix game not ending bug

* fix genome getting stuck bug

* fixed infinite while loop in tree search angents

* and fixed the same problem for DFS

* fixed possibly a problem with gameState.isGameOver

* added OpponentModel to MCTS, RHEA and PRHEA

* added playerID to heuristics since it could effect MCTS and other agents

* added << to portfolio scripts

* Trying out MetaPOAgent

* added opponent model to simple search agents

* Prototype for Multi-objective Portfolio RHEA

* added Portfolio Online Evolution

* fixed missing crowding distance calculation bug

* Changed class names of scripts and portfolios for consistency with related work

* added PortfolioTBSForwardModel and implemented it in BFS and BeamSearch

* added remaining fixes

* is there a bug with predicting holes and dying units?

* fixed a bug with preparing the PortfolioForwardModel

* updated MCTS Agent

Co-authored-by: Alexander Dockhorn <dockhorn.alexander@gmail.com>
Co-authored-by: Dominik Jeurissen <dominik.jeurissen@student.maastrichtuniversity.nl>

* add missing fixes for merging feat_agents (#7)

Co-authored-by: Dominik Jeurissen <dominik.jeurissen@student.maastrichtuniversity.nl>

* ActionSpaces now responsible for generating actions + ActionSpaces can be changed in the ForwardModel 

* Rename funcions for preparation of std::vector

* Replace ActionSpace with vector

* Fix errors introduced by std::vector

* Remove obsolete actionSpace class

* Replace Action<Vector2i> with TBSAction

* Replace Action<Vector2f> with RTSAction

* Remove Action.h

* Add ActionSpace to TBSForwardModel

* Add ActionSpace to RTSForwardModel

* Rename getActions to generateActions

* Fix CombatAgent

* Do not change config

Co-authored-by: Dominik Jeurissen <dominik.jeurissen@student.maastrichtuniversity.nl>

* Fix arena

Co-authored-by: Dominik Jeurissen <dominik.jeurissen@student.maastrichtuniversity.nl>

* Fix issues for compilation on mac

* Compiling on mac

1) cmakelists.txt

This doesn’t work on Mac:
add_compile_options("/std:c++latest")

This does:
if (WIN32 OR UNIX)
   set(COMPILER_FLAGS "")
elseif (APPLE)
   set(COMPILER_FLAGS "-Xclang -fconcepts-ts")
endif()

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${COMPILER_FLAGS}")

2) Extra Qualification Errors:
(example: git/Stratega/Stratega/include/Game/RTSGameCommunicator.h:30:29: error: extra qualification on member 'isGameOver'):
Solution: https://stackoverflow.com/questions/5642367/extra-qualification-error-in-c

3) Type error:
git/Stratega/Stratega/include/Representation/BuildContext.h:6:10: error: unknown type name '__int64'; did you mean '__int64_t'?
 Solution: use:
#include <cstdint>
...
typedef __int64_t TimeVal;

4) std:uniform_real:
git/Stratega/Stratega/include/Agent/RHEAAgent/RHEAAgent.h:21:8: error: no template named 'uniform_real' in namespace 'std'
Solution:
Change uniform_real<T> for uniform_real_distribution<T>
Some distributions were defined as const. Then, using the call dist(randomGenerator) gave this error:

error: no matching function for call to object of type 'const std::uniform_real_distribution<double>'

Removing the const in the definition of the distribution seemed to work. Please double check.

* Delete .gitignore.swp

* Further fixes

BuildContext.cpp:
#include <cstring>
#include <cstdarg>

TBSGame.cpp:
#include <thread>

* RenderLayer<GameState> specified here and there

* main() must return int

* Fixing non-const lvalue in git/Stratega/GUI/src/RTSGameStateRender.cpp:378

* CMAKE_OUTPUT_DIRS for win only. Also GUI and Tests receive YAML by parameter for cross-OS Compatibility

* using int64_t in BuildContext.h; override in MapLayer.h, and referencing base class members with this->

* Fixed Mac errors

* Compiling on mac

1) cmakelists.txt

This doesn’t work on Mac:
add_compile_options("/std:c++latest")

This does:
if (WIN32 OR UNIX)
   set(COMPILER_FLAGS "")
elseif (APPLE)
   set(COMPILER_FLAGS "-Xclang -fconcepts-ts")
endif()

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${COMPILER_FLAGS}")

2) Extra Qualification Errors:
(example: git/Stratega/Stratega/include/Game/RTSGameCommunicator.h:30:29: error: extra qualification on member 'isGameOver'):
Solution: https://stackoverflow.com/questions/5642367/extra-qualification-error-in-c

3) Type error:
git/Stratega/Stratega/include/Representation/BuildContext.h:6:10: error: unknown type name '__int64'; did you mean '__int64_t'?
 Solution: use:
#include <cstdint>
...
typedef __int64_t TimeVal;

4) std:uniform_real:
git/Stratega/Stratega/include/Agent/RHEAAgent/RHEAAgent.h:21:8: error: no template named 'uniform_real' in namespace 'std'
Solution:
Change uniform_real<T> for uniform_real_distribution<T>
Some distributions were defined as const. Then, using the call dist(randomGenerator) gave this error:

error: no matching function for call to object of type 'const std::uniform_real_distribution<double>'

Removing the const in the definition of the distribution seemed to work. Please double check.

* Delete .gitignore.swp

* Further fixes

BuildContext.cpp:
#include <cstring>
#include <cstdarg>

TBSGame.cpp:
#include <thread>

* RenderLayer<GameState> specified here and there

* main() must return int

* Fixing non-const lvalue in git/Stratega/GUI/src/RTSGameStateRender.cpp:378

* CMAKE_OUTPUT_DIRS for win only. Also GUI and Tests receive YAML by parameter for cross-OS Compatibility

* using int64_t in BuildContext.h; override in MapLayer.h, and referencing base class members with this->

* Move rendering to main-thread and gameRunner to a new gameThread

* Update main.cpp

Co-authored-by: Dominik Jeurissen <dominik.jeurissen@student.maastrichtuniversity.nl>

* Rework the Gamestate representation to a more general approach (Entity-Resource System) (#14)

Too much to list here => remember to create smaller changes

* Add skeleton for readTheDocs (#17)

Co-authored-by: Dominik Jeurissen <dominik.jeurissen@student.maastrichtuniversity.nl>

* Add Conditions and ValidTargets to OnTick-Trigger (#18)

Co-authored-by: Dominik Jeurissen <dominik.jeurissen@student.maastrichtuniversity.nl>

* Feat Technology Trees (#19)

* Add game featuring Capturing + Income Per Turn (#20)

* Implement Capturing Game

* Fix KillTheKing config

* Add OnEntitySpawn effect

* Add temporary display for playerParameters in TBS

* Fix merge bugs

* Add PlayerParameter to technology conditions/effects

Co-authored-by: Dominik Jeurissen <dominik.jeurissen@student.maastrichtuniversity.nl>

* Fix arena and tests

* Test game features

* Updated after discussion on 20/01/2021

* Back to original resolution

* Make GUI code standard conform (#25)

* Add continious actions (#24)

* Parse ContinuousActions

* Continuous Action working (OnStart, OnComplete, OnTick, TriggerComplete)

* Added ContinuousAction to ActionTarget

* Cleaned previous commits

* Now entity can abort continuous actions

* Cleaned and check the target conditions before executing OnComplete

* Cleaned

* Removed Abort action from yaml + Added Hardcoded abort action + Allow only one continuous action of the same type at the same time

* Execute first OnTick and then check if is TriggerComplete is true

* Remplaced bool isEndTick, isContinuousAction and isAbortContinuousAction with enum flags + Working in RTS and TBS

* Removed Hardcoded EndTurn in config parser

* Added info to Abort continue action in the actions window

* Cleaned Function parameter + fixed generating abort action before checking the conditions of the continuous action

* Feat improved fog of war (#26)

* Replace Board with a more general Grid2D implementation

* Implement new FogOfWar using isWalkable for blocking sight

* Add blocksSight flag to tiles

* Make line-algorithm a little bit more understandable

* Remove continious actions from protectTheBase

Co-authored-by: Dominik Jeurissen <dominik.jeurissen@student.maastrichtuniversity.nl>

* EntityTypes as actionTargets + RandomSpawn + Attaching Costs to Entities and Technologies (#27)

* Add EntityType Target & SpawnRandom action for TBS-Games

* Add canSpawn condition => currently relativly hardcoded

* Add cost to entityTypes and technologies

Co-authored-by: Dominik Jeurissen <dominik.jeurissen@student.maastrichtuniversity.nl>

* Feat player actions (#28)

* Parse ContinuousActions

* Continuous Action working (OnStart, OnComplete, OnTick, TriggerComplete)

* Added ContinuousAction to ActionTarget

* Cleaned previous commits

* Now entity can abort continuous actions

* Cleaned and check the target conditions before executing OnComplete

* Cleaned

* Parse player parameter and actionsIDs

* Removed Abort action from yaml + Added Hardcoded abort action + Allow only one continuous action of the same type at the same time

* Execute first OnTick and then check if is TriggerComplete is true

* Remplaced bool isEndTick, isContinuousAction and isAbortContinuousAction with enum flags + Working in RTS and TBS

* Removed Hardcoded EndTurn in config parser

* Added info to Abort continue action in the actions window

* Adding generation of player action

* Working on player action, should work + Activated TBS Gamecommunicator FoW and TBSGameStateRender FoW

* Show targets in Action window + We have to refactor everythiiiing

* Contninuous Actions works by player

* Add Civ-like game (#29)

* Make the noNameGame work

* Fix warrior

* Add new sprites

* Draft upload

* Update settler cost

* Fix Attack action attacking gold

* Added catapult sprite

* Clean gameConfigs

* Remove loading non-existing file in RTS

Co-authored-by: Dominik Jeurissen <dominik.jeurissen@student.maastrichtuniversity.nl>
Co-authored-by: Jorge Hurtado <r4z31996@gmail.com>

* Fix configfiles + Cleanup assets

* Added Basic Readme + Reorganized Sprites

* Updated readme + cleaned some functions

* Updated Readme

* Cleaned FunctionParameter + Effects + Conditions

Co-authored-by: Dominik Jeurissen <dominik.jeurissen@student.maastrichtuniversity.nl>
Co-authored-by: Dominik Jeurissen <10519507+CommanderCero@users.noreply.github.com>
Co-authored-by: Alexander Dockhorn <dockhorn.alexander@gmail.com>
Co-authored-by: GAIGResearch <35296018+GAIGResearch@users.noreply.github.com>
Co-authored-by: Jai Powles <jaipowles@me.com>